/**
 * Registry — đỏ_LP_kaishaintro (tp_biz63)
 * Thư mục gốc: frontend/template/đỏ_LP_kaishaintro/
 * Giữ nguyên toàn bộ HTML, css/, js/, images/, _manual/
 */

/** Tên thư mục trên disk (Unicode NFD) */
export const DO_LP_KAISHAINTRO_FOLDER = 'đ\u006f\u0309_LP_kaishaintro';

export const DO_LP_KAISHAINTRO_REGISTRY = {
  templateKey: 'do_lp_kaishaintro',
  folder: DO_LP_KAISHAINTRO_FOLDER,
  renderMode: 'html',
  layout: 'biz63',
  name: 'LP Kaisha Intro — Đỏ',
  description: 'Landing giới thiệu công ty / WEB制作 — hero, testimonial, portfolio, pricing, FAQ',
  previewColor: '#dc2626',
  assets: {
    css: ['css/style.css', 'css/inview.css'],
    js: ['js/jquery.inview_set.js', 'js/main.js'],
    externalJs: [
      'https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js',
      'https://cdnjs.cloudflare.com/ajax/libs/protonet-jquery.inview/1.1.2/jquery.inview.min.js',
    ],
    externalCss: [
      'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css',
    ],
  },
  sharedBlocks: {
    header: {
      id: 'header',
      type: 'header',
      label: 'Header & Menu',
      logoSelector: 'h1#logo a, #logo a',
      logoType: 'image',
      navSelector: 'header nav > ul',
    },
    footer: {
      id: 'footer',
      type: 'footer',
      label: 'Footer',
      addressSelector: 'footer > div:first-child p',
      menuSelector: 'footer ul',
      copyrightSelector: 'footer small',
      snsSelector: 'footer .icons',
    },
    hero: {
      id: 'mainimg',
      type: 'hero_slide',
      label: 'Hero / Main image',
      selector: '#mainimg',
      fields: ['headline', 'ctaPrimary', 'ctaSecondary'],
      defaultSlide: {
        headline: '見る人を惹きつける、\nワンランク上の\nWEBサイトを制作',
        ctaPrimary: 'お問い合わせ',
        ctaSecondary: '資料請求',
        ctaPrimaryHref: 'contact.html',
        ctaSecondaryHref: '#',
        ctaPrimaryIcon: 'fa-regular fa-envelope',
        ctaSecondaryIcon: 'fa-regular fa-file-lines',
      },
    },
  },
  nav: [
    { label: 'お客様の声', pageId: 'index', href: 'index.html#koe', anchor: 'koe' },
    { label: '制作実績', pageId: 'index', href: 'index.html#products', anchor: 'products' },
    { label: '料金プラン', pageId: 'index', href: 'index.html#plan', anchor: 'plan' },
    { label: 'よく頂く質問', pageId: 'index', href: 'index.html#faq', anchor: 'faq' },
    { label: '制作の流れ', pageId: 'index', href: 'index.html#flow', anchor: 'flow' },
    { label: 'お問い合わせ', pageId: 'contact', href: 'contact.html' },
  ],
  pages: [
    {
      id: 'index',
      file: 'index.html',
      slug: '',
      title: 'Trang chủ',
      titleJa: 'HOME',
      isHome: true,
      category: 'main',
      hasHero: true,
      bodyClass: '',
      layout: 'single-page-scroll',
      description: 'Landing 1 trang: hero, pain points, solutions, testimonials, portfolio, pricing, FAQ, flow, company, news',
      previewImage: `/template/${encodeURIComponent(DO_LP_KAISHAINTRO_FOLDER)}/images/bg_works.jpg`,
      sections: [
        { id: 'hero', type: 'hero_slide', ref: 'sharedBlocks.hero', label: 'Hero / Main image' },
        {
          id: 'problems',
          type: 'icon_list',
          label: 'Pain points (お悩み)',
          selector: 'section.bg-pattern1.arrow .list-grid1',
          heading: { main: 'こんなお悩みありませんか？', sub: 'Do you have any of these problems?' },
          items: [
            { title: 'デザインが古くて、他社と比べて見劣りしている…', body: 'サイト制作からもう15年。自分で見ていてもさすがに古さを実感するようになった。', image: 'images/icon1.png' },
            { title: '予算内で、どこまで実現できるのか不安…', body: '予算が限られているのでサイト制作をしてくれる業者が見つかるか不安。', image: 'images/icon2.png' },
            { title: '売上につながるサイト運営のアドバイスが欲しい…', body: 'リニューアルするだけじゃなく、その後のステップアップのサポートもしてくれるような業者を見つけたい。', image: 'images/icon3.png' },
          ],
        },
        {
          id: 'solutions',
          type: 'icon_list',
          label: 'Solutions (解決)',
          selector: 'section.bg-primary-color:not(#faq) .list-grid1',
          heading: { main: '全てサンプルカンパニーが解決します！', sub: '' },
          items: [
            { title: '最新トレンドで差をつける', body: '1000件以上の制作実績を持つクリエイターが、貴社の強みと最新デザインを組み合わせたWEBサイトをご提案します。', image: 'images/icon1.png' },
            { title: '安心の定額制プラン', body: '必要な機能と優先順位を明確化し、段階的な開発計画をご提案。', image: 'images/icon2.png' },
            { title: '成果を生み出す伴走支援', body: '制作後もアクセス解析とユーザー行動の調査結果をもとに、具体的な改善施策をご提案。', image: 'images/icon3.png' },
          ],
        },
        {
          id: 'testimonials',
          type: 'testimonials_scroll',
          label: 'Testimonials (お客様の声)',
          selector: '#koe .list-normal1',
          anchor: 'koe',
          heading: { main: 'お客様の声', sub: 'Customer Testimonials' },
          items: [
            { title: 'IT企業の強みが伝わるサイトで採用力アップ', body: 'ベンチャー企業らしい先進的なデザインと、技術力が伝わるコンテンツ作りが秀逸でした。', image: 'images/photo1.jpg', name: '株式会社〇〇 代表取締役 中村様' },
            { title: '社員の魅力が伝わるサイトで会社の雰囲気が一新', body: '女性社員が多い当社の魅力を、スタッフインタビューや福利厚生の紹介で上手く表現していただきました。', image: 'images/photo2.jpg', name: '株式会社〇〇 代表取締役 吉田様' },
            { title: 'インスタ映えするカフェの世界観をサイトでも表現', body: '写真の見せ方や色使いなど、カフェの雰囲気を完璧に表現していただき感動しました。', image: 'images/photo3.jpg', name: '〇〇 Cafe オーナー 木村様' },
          ],
          moreLink: { text: 'もっと見る', href: '#' },
        },
        {
          id: 'products',
          type: 'list_grid',
          label: 'Portfolio (制作実績)',
          selector: '#products .list-grid-simple',
          anchor: 'products',
          heading: { main: '制作実績', sub: 'Production Achievements' },
          items: [
            { title: '株式会社〇〇様', image: 'images/thumb1.jpg' },
            { title: '株式会社〇〇様', image: 'images/thumb2.jpg' },
            { title: '株式会社〇〇様', image: 'images/thumb3.jpg' },
            { title: '株式会社〇〇様', image: 'images/thumb4.jpg' },
            { title: '株式会社〇〇様', image: 'images/thumb5.jpg' },
            { title: '株式会社〇〇様', image: 'images/thumb6.jpg' },
          ],
          moreLink: { text: 'もっと見る', href: '#' },
        },
        {
          id: 'plan',
          type: 'pricing_table',
          label: 'Pricing (料金プラン)',
          selector: '#plan',
          anchor: 'plan',
          heading: { main: '料金プラン', sub: 'Rate Plans' },
          plans: [
            { name: 'エコノミープラン', price: '50,000', icon: 'fa-solid fa-crown' },
            { name: 'スタンダードプラン', price: '100,000', icon: 'fa-solid fa-crown', badge: 'おすすめ' },
            { name: 'プレミアムプラン', price: '300,000', icon: 'fa-solid fa-crown' },
          ],
          rows: [
            { label: 'ページ数', values: ['5ページまで', '10ページまで', '20ページまで'] },
            { label: 'デザイン案', values: ['1案を提案', '2案を提案', '3案を提案'] },
            { label: 'サポート期間', values: ['1ヶ月間', '3ヶ月間', '6ヶ月間'] },
          ],
        },
        {
          id: 'faq',
          type: 'faq_accordion',
          label: 'FAQ',
          selector: '#faq dl.faq',
          anchor: 'faq',
          heading: { main: 'よく頂く質問', sub: 'FAQ' },
          items: [
            { question: 'ここに質問を書きます。クリックで回答が開きます。', answer: 'ここに回答を書きます。サンプルテキスト。' },
            { question: 'ここに質問を書きます。クリックで回答が開きます。', answer: 'ここに回答を書きます。サンプルテキスト。' },
          ],
        },
        {
          id: 'flow',
          type: 'step_list',
          label: 'Flow (制作の流れ)',
          selector: '#flow .list-normal1.flow',
          anchor: 'flow',
          heading: { main: '制作の流れ', sub: 'Production Flow' },
          steps: [
            { title: 'ヒアリング', body: 'お客様のビジネス内容やサイト制作の目的をしっかりとお伺いします。', icon: 'fa-solid fa-ear-listen' },
            { title: 'デザイン制作', body: 'ヒアリング内容をもとに、お客様のブランドに最適なデザイン案を作成します。', icon: 'fa-solid fa-palette' },
            { title: 'コーディング', body: '確定したデザインをHTML、CSS、JavaScriptを使用してコーディングします。', icon: 'fa-solid fa-code' },
            { title: '公開＆サポート', body: '完成したサイトをサーバーにアップロードし、正式に公開します。', icon: 'fa-solid fa-globe' },
          ],
        },
        {
          id: 'text_slide',
          type: 'text_marquee',
          label: 'Text marquee',
          selector: '.text-slide-wrapper',
          decorative: true,
        },
        {
          id: 'company',
          type: 'company_profile',
          label: 'Company (会社概要)',
          selector: '#company',
          anchor: 'company',
          heading: { main: '会社概要', sub: 'Company' },
          caption: '大見出しが必要ならここを使います',
          rows: [
            { label: '見出し', value: 'ここに説明など入れて下さい。サンプルテキスト。' },
            { label: '見出し', value: 'ここに説明など入れて下さい。サンプルテキスト。' },
            { label: '見出し', value: 'ここに説明など入れて下さい。サンプルテキスト。' },
            { label: '見出し', value: 'ここに説明など入れて下さい。サンプルテキスト。' },
            { label: '見出し', value: 'ここに説明など入れて下さい。サンプルテキスト。' },
          ],
        },
        {
          id: 'contact_cta',
          type: 'dual_cta',
          label: 'Contact & Request CTA',
          selector: 'section.padding0 .list-c2',
          buttons: [
            { text: 'お問い合わせフォーム', href: 'contact.html', subText: 'お問い合わせ', mainText: 'Contact' },
            { text: '資料請求フォーム', href: '#', subText: '資料請求', mainText: 'Request' },
          ],
        },
        {
          id: 'news',
          type: 'news_list',
          label: 'News (お知らせ)',
          selector: 'dl.new',
          heading: { main: 'お知らせ', sub: 'News' },
          items: [
            { date: '2000/00/00', tag: 'その他', body: 'サンプルテキスト。サンプルテキスト。' },
            { date: '2000/00/00', tag: '重要', body: 'サンプルテキスト。サンプルテキスト。' },
          ],
        },
        {
          id: 'thumbnail_slide',
          type: 'thumbnail_marquee',
          label: 'Thumbnail slideshow',
          selector: 'section.padding-lr0',
          decorative: true,
        },
        {
          id: 'template_notice',
          type: 'raw_html',
          label: 'Template notice (ẩn mặc định)',
          selector: 'main > section:last-of-type',
          decorative: true,
          visible: false,
        },
      ],
    },
    {
      id: 'contact',
      file: 'contact.html',
      slug: 'contact',
      title: 'Liên hệ',
      titleJa: 'CONTACT',
      isHome: false,
      category: 'main',
      hasHero: false,
      layout: 'single-column',
      description: 'Trang mẫu form liên hệ',
      sections: [
        {
          id: 'contact_sample',
          type: 'contact_form',
          label: 'Form liên hệ (mẫu)',
          selector: 'main section form',
          heading: { main: 'お問い合わせ', sub: 'Contact' },
          fields: [
            { key: 'name', label: 'お名前', required: true, type: 'text' },
            { key: 'email', label: 'メールアドレス', required: true, type: 'email' },
            { key: 'message', label: 'お問い合わせ詳細', required: true, type: 'textarea' },
          ],
          submitText: '内容を確認する',
        },
      ],
    },
    {
      id: 'form',
      file: 'form.html',
      slug: 'form',
      title: 'Form gửi',
      titleJa: 'FORM',
      isHome: false,
      category: 'form-flow',
      hasHero: false,
      layout: 'single-column',
      description: 'Form gửi thực tế (form.html)',
      sections: [
        {
          id: 'contact_form',
          type: 'contact_form',
          label: 'Form liên hệ',
          selector: 'main section form',
          heading: { main: 'お問い合わせ', sub: 'Contact' },
          fields: [
            { key: 'name', label: 'お名前', required: true, type: 'text' },
            { key: 'email', label: 'メールアドレス', required: true, type: 'email' },
            { key: 'message', label: 'お問い合わせ内容', required: true, type: 'textarea' },
          ],
          submitText: '内容を確認する',
        },
      ],
    },
    {
      id: 'confirm',
      file: 'confirm.html',
      slug: 'confirm',
      title: 'Xác nhận',
      titleJa: 'CONFIRM',
      isHome: false,
      category: 'form-flow',
      hasHero: false,
      layout: 'single-column',
      description: 'Trang xác nhận form (confirm.html)',
      sections: [
        {
          id: 'confirm_view',
          type: 'contact_form',
          label: 'Xác nhận nội dung',
          selector: 'main section',
          heading: { main: '内容確認', sub: 'Confirm' },
        },
      ],
    },
    {
      id: 'finish',
      file: 'finish.html',
      slug: 'finish',
      title: 'Hoàn tất',
      titleJa: 'FINISH',
      isHome: false,
      category: 'form-flow',
      hasHero: false,
      layout: 'single-column',
      description: 'Trang hoàn tất gửi form (finish.html)',
      sections: [
        {
          id: 'finish_message',
          type: 'cta_banner',
          label: 'Thông báo hoàn tất',
          selector: 'main section',
          heading: { main: '送信完了', sub: 'Finish' },
          body: 'お問い合わせありがとうございました。',
        },
      ],
    },
    {
      id: '_manual',
      file: '_manual/manual.html',
      slug: '_manual',
      title: 'Manual',
      category: 'system',
      isHome: false,
      hasHero: false,
      hidden: true,
      description: 'Hướng dẫn sử dụng template (_manual/)',
      sections: [],
    },
  ],
};

export default DO_LP_KAISHAINTRO_REGISTRY;
