/**
 * Registry — lp_recruite / lp_a01
 * Thư mục: frontend/template/lp_recruite/lp_a01/
 * Trang tuyển dụng 1 page scroll: company, work, people, recruit, entry
 */

export const LP_RECRUITE_FOLDER = 'lp_recruite/lp_a01';

export const LP_RECRUITE_REGISTRY = {
  templateKey: 'lp_recruite',
  folder: LP_RECRUITE_FOLDER,
  renderMode: 'html',
  layout: 'recruit',
  name: 'LP Recruite — Tuyển dụng',
  description: 'Site tuyển dụng — hero slide, company, work, people, recruit info, entry',
  previewColor: '#0f766e',
  assets: {
    css: ['css/common.css', 'css/custom.css'],
    js: ['js/common.js'],
  },
  sharedBlocks: {
    header: {
      id: 'header',
      type: 'header',
      label: 'Header & Menu',
      logoSelector: '.company_name_box a, h1.company_name',
      logoType: 'text',
      navSelector: 'header nav > ul',
      entrySelector: '.entry_btn a',
    },
    footer: {
      id: 'footer',
      type: 'footer',
      label: 'Footer',
      copyrightSelector: 'footer .copyright',
    },
    hero: {
      id: 'hero',
      type: 'recruit_hero',
      label: 'Hero slide',
      selector: '.slide_hero',
      defaultSlide: {
        headline: '一緒に進化し続けよう',
        subheadline: 'EVOLVE\nTOGETHER',
        body: 'システムエンジニア・プログラマー募集',
      },
      defaultSlides: [
        { image: 'img/00_01.jpg' },
        { image: 'img/00_02.jpg' },
        { image: 'img/00_03.jpg' },
      ],
    },
  },
  nav: [
    { label: '会社を知る', pageId: 'index', anchor: 'company' },
    { label: '仕事を知る', pageId: 'index', anchor: 'work' },
    { label: '人を知る', pageId: 'index', anchor: 'people' },
    { label: '採用情報', pageId: 'index', anchor: 'recruit' },
    { label: 'ENTRY', pageId: 'index', anchor: 'entry' },
  ],
  pages: [
    {
      id: 'index',
      file: 'index.html',
      slug: '',
      title: 'Trang chủ',
      titleJa: 'RECRUIT',
      isHome: true,
      category: 'main',
      hasHero: true,
      layout: 'single-page-scroll',
      description: 'Landing tuyển dụng 1 trang: hero, news, message, company, work, people, recruit, entry',
      previewImage: `/template/${LP_RECRUITE_FOLDER.replace('/', '%2F')}/img/02.jpg`,
      sections: [
        { id: 'hero', type: 'recruit_hero', ref: 'sharedBlocks.hero', label: 'Hero slide' },
        {
          id: 'news',
          type: 'recruit_news',
          label: 'Thông báo',
          selector: '.news_block',
          heading: { main: 'お知らせ' },
          body: '採用サイトをリニューアルいたしました。',
        },
        {
          id: 'message',
          type: 'text_image',
          label: 'Message',
          selector: '.message_box',
          heading: { main: '新たなステージへ挑戦' },
          body: '私たちは、次世代のシステムエンジニアを募集しています。\nあなたの経験とスキルを活かし、共に新たなステージに挑戦しましょう。\n当社では、自由な発想とチャレンジ精神を尊重し、個々の成長をサポートする環境が整っています。\n私たちと一緒に、未来を切り拓いていきましょう。',
        },
        {
          id: 'company',
          type: 'recruit_page',
          label: 'Company (会社を知る)',
          selector: '#company',
          anchor: 'company',
          sectionLabel: 'COMPANY',
          heading: { main: '会社を知る', sub: '信頼性の高いシステムを提供' },
          copyHeadline: 'お客様のビジネスを支えるための最先端のシステムソリューションを提供しています。',
          copyBody: '技術革新を推進する当社では、システムエンジニアが主役です。\n高度なトレーニングプログラムやメンター制度を通じて、あなたのスキルアップをサポートします。\nプロジェクトごとに異なる課題を解決し、クライアントの期待を超える成果を追求しています。',
        },
        {
          id: 'company_services',
          type: 'icon_list',
          label: 'Company — Dịch vụ',
          selector: '#company .company_box > div:last-child',
          items: [
            { title: 'システム開発', body: 'クライアントのニーズに合わせたカスタムシステムを提供します。' },
            { title: 'セキュリティ対策', body: '情報セキュリティの強化とリスク管理をサポートします。' },
            { title: 'ITコンサルティング', body: '最適なITソリューションを提案し、導入支援を行います。' },
            { title: 'システム保守・運用', body: '導入後のシステムの運用サポートと保守サービス。' },
          ],
        },
        {
          id: 'company_profile',
          type: 'company_profile',
          label: 'Company — Bảng thông tin',
          selector: '#company .grid_2',
          rows: [
            { label: '会社名', value: '株式会社SAMPLE' },
            { label: '設立', value: '20XX年X月X日' },
            { label: '代表者', value: '代表取締役社長 東京太郎' },
            { label: '資本金', value: '10,000,00円' },
            { label: '事業内容', value: 'システム開発、ソフトウェア開発、ITコンサルティング、システム保守・運用' },
            { label: 'ホームページ', value: 'https://www.saiyo-sample.com' },
            { label: '所在地', value: '123-4567 東京都渋谷区桜丘町1-2-3' },
            { label: '主要取引先', value: '株式会社SAMPLE、株式会社DEF、株式会社GHI' },
            { label: '取引銀行', value: '三井住友銀行 渋谷支店' },
            { label: '従業員数', value: '200名（2024年現在）' },
          ],
        },
        {
          id: 'company_stats',
          type: 'recruit_stats',
          label: 'Company — Số liệu nội bộ',
          selector: '#company .data_box',
          items: [
            { title: '従業員数', value: '36', valueTarget: 36, unit: '名', image: 'img/icon-56.png' },
            { title: '平均年齢', value: '42', valueTarget: 42, unit: '歳', image: 'img/icon-7.png' },
            { title: '有給休暇取得率', value: '92', valueTarget: 92, unit: '%', image: 'img/icon-57.png' },
            { title: '平均残業時間', value: '15', valueTarget: 15, unit: '時間', image: 'img/icon-51.png' },
            { title: '離職率', value: '4', valueTarget: 4, unit: '%', image: 'img/icon-76.png' },
            { title: '平均勤続年数', value: '15', valueTarget: 15, unit: '年', image: 'img/icon-52.png' },
            { title: '年間休日', value: '115', valueTarget: 115, unit: '日', image: 'img/icon-16.png' },
            { title: '育児休暇取得率', value: '100', valueTarget: 100, unit: '%', image: 'img/icon-11.png' },
            { title: '女性比率', value: '40', valueTarget: 40, unit: '%', image: 'img/icon-9.png' },
            { title: '他業種からの転職率', value: '45', valueTarget: 45, unit: '%', image: 'img/icon-40.png' },
            { title: 'リモートワーク率', value: '34', valueTarget: 34, unit: '%', image: 'img/icon-88.png' },
            { title: 'お弁当持参率', value: '63', valueTarget: 63, unit: '%', image: 'img/icon-55.png' },
          ],
        },
        {
          id: 'work',
          type: 'recruit_page',
          label: 'Work (仕事を知る)',
          selector: '#work',
          anchor: 'work',
          sectionLabel: 'WORK',
          heading: { main: '仕事を知る', sub: 'システム企画から開発・運用・保守' },
          copyHeadline: '最新のトレンドに対応することが求められるため、自己成長を実感できます。',
          copyBody: 'システムエンジニアの仕事は、日々の業務を通じて新たなチャレンジに満ちています。\nクライアントとの打ち合わせ、システムの設計・開発、テスト、そして導入後のフォローアップまで、\n一つのプロジェクトには多くのステップがあります。\n多彩な業務を経験しながら、自身のスキルを高めることができる環境で、あなたの成長をサポートします。',
        },
        {
          id: 'work_flow',
          type: 'step_list',
          label: 'Work — Quy trình',
          selector: '#work .work_flow_box',
          steps: [
            { title: '要件定義', body: 'クライアントとの打ち合わせを通じて、システムの機能や性能、使用目的などの要件を明確にする。', step: '1' },
            { title: '設計', body: '要件に基づき、システム全体の構造や各機能の設計を行う。詳細設計書を作成し、実装の準備を整える。', step: '2' },
            { title: '開発・プログラミング', body: '設計書に従って、プログラムのコーディングを行い、必要な機能を実装する。', step: '3' },
            { title: 'テスト', body: '開発したシステムが要件通りに動作するかを確認するためのテストを実施。不具合があれば修正する。', step: '4' },
            { title: '導入・運用保守', body: 'システムをクライアントの環境に導入し、運用開始後のサポートや定期的なメンテナンスを行う。', step: '5' },
          ],
        },
        {
          id: 'work_images',
          type: 'list_grid',
          label: 'Work — Ảnh minh họa',
          selector: '#work .work_flow_img',
          items: [
            { title: 'クライアントからのフィードバックを受け、システムの改善を行います。', image: 'img/04.jpg' },
            { title: 'システムの運用をサポートし、定期的な保守を行います。', image: 'img/05.jpg' },
          ],
        },
        {
          id: 'people',
          type: 'recruit_page',
          label: 'People (人を知る)',
          selector: '#people',
          anchor: 'people',
          sectionLabel: 'PEOPLE',
          heading: { main: '人を知る', sub: 'チームとの連携や成長' },
          copyHeadline: 'ITの力で未来を描く、エンジニアの素顔',
          copyBody: '私たちは、単なる技術者ではなく、ビジネスの課題を解決するプロフェッショナルです。\nお客様と共に未来を見据え、新しい価値を創造するために日々努力しています。\nその裏側には、確かな技術力と創造力が息づいています。',
        },
        {
          id: 'people_profile',
          type: 'testimonials_scroll',
          label: 'People — Staff voice',
          selector: '#people .people_voice_box',
          items: [
            {
              title: '最先端の技術に触れながら\n自己成長できる環境',
              body: 'システムエンジニア 2018年入社',
              name: 'S.K.さん',
              image: 'img/07.jpg',
            },
          ],
        },
        {
          id: 'people_qa',
          type: 'recruit_qa',
          label: 'People — Q&A phỏng vấn',
          selector: '#people .people_voice',
          items: [
            { question: 'システムエンジニアとして働く中で最もやりがいを感じる瞬間は？', answer: 'やはり、自分が開発したシステムがクライアントの業務に役立ち、喜んでもらえた時です。' },
            { question: '日々の業務で大切にしていることは何ですか？', answer: 'コミュニケーションです。クライアントの要望を正確に理解し、それをチーム内で共有することが、プロジェクトの成功に不可欠です。' },
            { question: '困難に直面した時、どのように乗り越えていますか？', answer: '困難に直面した時は、まず冷静に状況を分析し、原因を特定します。その後、チームメンバーと協力しながら解決策を模索します。' },
          ],
        },
        {
          id: 'people_timeline',
          type: 'recruit_timeline',
          label: 'People — Lịch 1 ngày',
          selector: '#people .table_timeline tbody',
          items: [
            { time: '9:00', title: '出社・メールチェック', body: 'コミュニケーションです。クライアントの要望を正確に理解し、それをチーム内で共有することが、プロジェクトの成功に不可欠です。' },
            { time: '10:00', title: '朝のミーティング', body: 'チームメンバーとのデイリースクラムやスタンドアップミーティングに参加します。' },
            { time: '11:00', title: 'コーディングセッション', body: '主要なプロジェクトやタスクに取り組み、コーディングを行います。' },
            { time: '12:30', title: 'ランチ休憩', body: '同僚と一緒にランチを楽しみながらリフレッシュします。' },
            { time: '13:30', title: 'コーディング再開', body: '午前中に続いてコーディングを行います。' },
            { time: '15:00', title: 'コードレビュー', body: '同僚のコードをレビューし、フィードバックを提供します。' },
            { time: '16:00', title: '技術ミーティング・ドキュメント作成', body: 'プロジェクトの技術的な課題や設計についてのミーティングに参加します。' },
            { time: '17:30', title: '終業準備・日報作成', body: '一日の業務をまとめ、日報を作成します。' },
          ],
        },
        {
          id: 'parallax',
          type: 'text_marquee',
          label: 'Parallax text',
          selector: '.parallax',
          decorative: true,
        },
        {
          id: 'recruit',
          type: 'recruit_page',
          label: 'Recruit (採用情報)',
          selector: '#recruit',
          anchor: 'recruit',
          sectionLabel: 'RECRUIT',
          heading: { main: '採用情報', sub: 'スキルを活かせる職場' },
          copyHeadline: '技術の未来を共に創る！システムエンジニア募集',
          copyBody: '革新的な技術を通じて社会に貢献するシステムエンジニアを募集しています。\n最先端のプロジェクトに携わりながら、自己成長を図りたい方にぴったりの環境です。\n多様な業界と連携し、チームワークを大切にしながら一緒に働きませんか？\nあなたの技術と情熱を活かし、次世代のシステムを共に開発しましょう！',
        },
        {
          id: 'recruit_table',
          type: 'company_profile',
          label: 'Recruit — Bảng tuyển dụng',
          selector: '#recruit .table_recruit',
          rows: [
            { label: '募集職種', value: 'システムエンジニア' },
            { label: '仕事内容', value: '・システムの設計、開発、運用、保守\n・クライアントとの要件定義、仕様策定' },
            { label: '応募資格', value: '・システム開発の実務経験（3年以上）\n・Java、C#、Pythonなどのプログラミングスキル' },
            { label: '歓迎スキル・経験', value: '・クラウドサービス（AWS、Azureなど）の利用経験' },
            { label: '勤務地', value: '・東京本社（リモートワーク可）' },
            { label: '勤務時間', value: '・9:00～18:00（フレックスタイム制あり）' },
            { label: '給与', value: '・年収500万円～800万円（経験・能力に応じて決定）' },
            { label: '福利厚生', value: '・各種社会保険完備\n・交通費全額支給' },
            { label: '応募方法', value: 'ENTRYよりご希望の応募方法をお選んで応募ください。' },
            { label: 'お問い合わせ', value: '・採用担当：鈴木\n・メール：recruit@saiyo-sample.com' },
          ],
        },
        {
          id: 'entry',
          type: 'recruit_entry',
          label: 'Entry (ứng tuyển)',
          selector: '#entry',
          anchor: 'entry',
          entryTitle: 'ENTRY',
          heading: { main: '日々の成長を実感、1年後大きく成長できる。' },
          body: 'ご希望の応募方法を以下よりお選びください。\n内容を確認後、採用担当者より折り返しご連絡させていただきます。',
          email: 'E-mail:recruit@saiyo-sample.com<span>（24時間受付）</span>',
          phone: 'TEL:03-1234-567X<span>採用担当：鈴木（10:00〜17:00）</span>',
          buttons: [
            { label: 'ENTRY', description: '就職・転職ナビサイト', href: '#' },
            { label: 'LINE', description: '公式LINEアカウント', href: '#' },
            { label: 'FORM', description: 'Googleフォーム', href: '#' },
          ],
        },
      ],
    },
  ],
};

export default LP_RECRUITE_REGISTRY;
