/**
 * Registry — xanh đậm_tối_LP_business_kaishaintro (tp_biz65)
 * Thư mục: frontend/template/xanh đậm_tối_LP_business_kaishaintro/
 */

export const XANH_DARK_LP_KAISHAINTRO_FOLDER = 'xanh \u0111a\u0323\u0302m_to\u0302\u0301i_LP_business_kaishaintro';

export const XANH_DARK_LP_KAISHAINTRO_REGISTRY = {
  templateKey: 'xanh_dark_lp_kaishaintro',
  folder: XANH_DARK_LP_KAISHAINTRO_FOLDER,
  renderMode: 'html',
  layout: 'biz65',
  name: 'LP Kaisha Intro — Xanh đậm',
  description: 'Corporate tp_biz65 — hero slideshow, services, strengths, workflow, news, contact',
  previewColor: '#1e3a5f',
  assets: {
    css: ['css/style.css'],
    js: ['js/jquery.inview_set.js', 'js/main.js'],
    externalJs: [
      'https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js',
      'https://cdnjs.cloudflare.com/ajax/libs/protonet-jquery.inview/1.1.2/jquery.inview.min.js',
    ],
    externalCss: [
      'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css',
    ],
  },
  sharedBlocks: {
    header: {
      id: 'header',
      type: 'header',
      label: 'Header & Menu',
      logoSelector: 'h1.logo a, .logo a',
      logoType: 'image',
      navSelector: 'header nav > ul',
    },
    footer: {
      id: 'footer',
      type: 'footer',
      label: 'Footer',
      addressSelector: 'footer > div:first-child p',
      menuSelector: 'footer .menu',
      copyrightSelector: 'footer small',
      snsSelector: 'footer .sns',
    },
    hero: {
      id: 'hero',
      type: 'hero_biz65',
      label: 'Hero slideshow',
      selector: '.mainimg',
      defaultSlide: {
        headline: '人の力で、\n未来をつくる。',
        body: '私たちは、はたらく人と企業の可能性を信じ、課題に向き合い、価値ある未来を共につくります。',
        ctaPrimary: '私たちについて',
        ctaSecondary: 'サービスを見る',
        ctaPrimaryHref: 'about.html',
        ctaSecondaryHref: 'service.html',
      },
      defaultSlides: [
        { slideClass: 'img1', image: 'images/mainimg1.jpg', imageMobile: 'images/mainimg1_s.jpg' },
        { slideClass: 'img2', image: 'images/mainimg2.jpg', imageMobile: 'images/mainimg2_s.jpg' },
        { slideClass: 'img3', image: 'images/mainimg3.jpg', imageMobile: 'images/mainimg3_s.jpg' },
      ],
    },
  },
  nav: [
    { label: '私たちについて', pageId: 'index', anchor: 'link1' },
    { label: 'サービス', pageId: 'index', anchor: 'link2' },
    { label: 'プロフィール', pageId: 'index', anchor: 'link3' },
    { label: '私たちの強み', pageId: 'index', anchor: 'link4' },
    { label: 'ご支援の流れ', pageId: 'index', anchor: 'link5' },
    { label: 'お問い合わせ', pageId: 'contact', href: 'contact.html' },
  ],
  pages: [
    {
      id: 'index',
      file: 'index.html',
      slug: '',
      title: 'Trang chủ',
      titleJa: 'HOME',
      isHome: true,
      category: 'main',
      hasHero: true,
      bodyClass: 'home',
      layout: 'single-page-scroll',
      description: 'Landing tp_biz65: hero, concept, services, people, strengths, workflow, gallery, news, contact CTA',
      previewImage: `/template/${encodeURIComponent(XANH_DARK_LP_KAISHAINTRO_FOLDER)}/images/mainimg1.jpg`,
      sections: [
        { id: 'hero', type: 'hero_biz65', ref: 'sharedBlocks.hero', label: 'Hero slideshow' },
        {
          id: 'concept',
          type: 'text_image',
          label: 'Concept (私たちについて)',
          selector: '#link1 .flex1',
          anchor: 'link1',
          heading: { main: '人に寄り添い、\n事業の成長をともに。', sub: 'OUR CONCEPT' },
          body: '変化の激しい時代だからこそ、私たちは「人」を起点に、企業の成長を支えるパートナーでありたいと考えています。対話を重ね、課題の本質を見つめ、最適なソリューションをともに描き、実行します。',
          image: 'images/concept.jpg',
          buttonText: '私たちの思い',
          buttonLink: 'about.html',
        },
        {
          id: 'services',
          type: 'icon_list',
          label: 'Services (事業内容)',
          selector: '#link2 .list1',
          anchor: 'link2',
          heading: { main: '事業内容', sub: 'SERVICES' },
          intro: '人と組織の成長を支える、3つのサービスを柱に、さまざまな課題解決をサポートします。',
          items: [
            { title: '組織・人事コンサルティング', body: '組織の課題を可視化し、戦略設計から実行までを伴走支援します。', icon: 'fas fa-people-group', href: 'service.html' },
            { title: '採用支援・人材紹介', body: '採用戦略の設計から人材紹介まで、最適なマッチングを実現します。', icon: 'fas fa-magnifying-glass-chart', href: 'service.html' },
            { title: '人材育成・研修サービス', body: '個人と組織の成長を支える研修やワークショップを提供します。', icon: 'fas fa-chart-line', href: 'service.html' },
          ],
        },
        {
          id: 'people',
          type: 'text_image',
          label: 'People (プロフィール)',
          selector: '#link3 .flex1',
          anchor: 'link3',
          heading: { main: '人が主役の、\nチームでありたい。', sub: 'PEOPLE' },
          body: '一人ひとりの個性や強みを尊重し、互いに支え合う文化を大切にしています。多様なバックグラウンドを持つメンバーが、同じ想いで未来に向かって歩んでいます。',
          image: 'images/people.webp',
          buttonText: 'メンバーを見る',
          buttonLink: 'people.html',
        },
        {
          id: 'strengths',
          type: 'list_grid',
          label: 'Strengths (私たちの強み)',
          selector: '#link4 .list1',
          anchor: 'link4',
          heading: { main: '私たちの強み', sub: 'STRENGTHS' },
          items: [
            { title: '対話力', body: '丁寧な対話を通じて、表面的な課題ではなく、本質的なニーズを引き出します。', image: 'images/strengths1.jpg', linkText: '詳しく見る', href: 'about.html' },
            { title: '提案力', body: '幅広い知見と最新の知識を掛け合わせ、最適なソリューションをご提案します。', image: 'images/strengths2.jpg', linkText: '詳しく見る', href: 'about.html' },
            { title: '伴走力', body: '実行フェーズまで寄り添い、成果につながるまで継続的にサポートします。', image: 'images/strengths3.jpg', linkText: '詳しく見る', href: 'about.html' },
          ],
        },
        {
          id: 'workflow',
          type: 'step_list',
          label: 'Workflow (ご支援の流れ)',
          selector: '#link5 .list2',
          anchor: 'link5',
          heading: { main: 'ご支援の流れ', sub: 'WORK FLOW' },
          intro: 'お客様の課題に寄り添い、課題の特定から実行支援まで一貫してサポートします。',
          steps: [
            { step: '01', title: 'ヒアリング', body: '現状や課題、ご要望を丁寧にお伺いします。', icon: 'fas fa-comments' },
            { step: '02', title: '課題整理', body: '課題を整理・分析し、解決すべきポイントを明確にします。', icon: 'fa-regular fa-file-lines' },
            { step: '03', title: 'ご提案', body: '最適な施策・プランをご提案し、期待される効果をご共有します。', icon: 'fas fa-chalkboard-user' },
            { step: '04', title: '実行支援', body: '実行計画の策定から実行まで、継続的に伴走します。', icon: 'fas fa-handshake' },
          ],
          footnote: '※内容やご状況により、プロセスは柔軟にカスタマイズいたします。',
        },
        {
          id: 'gallery',
          type: 'thumbnail_marquee',
          label: 'Gallery marquee',
          selector: '.bleed-x-parts',
          decorative: true,
        },
        {
          id: 'news',
          type: 'news_list',
          label: 'News (お知らせ)',
          selector: 'section.bg-parts.bg1-light-parts.mb0 dl.news',
          heading: { main: 'お知らせ', sub: 'NEWS' },
          items: [
            { date: '2026/06/05', body: 'ビジネス・一般企業向け 無料ホームページテンプレート tp_biz65 公開。' },
            { date: '2000/00/00', body: 'サンプルテキスト。サンプルテキスト。サンプルテキスト。' },
            { date: '2000/00/00', body: 'サンプルテキスト。サンプルテキスト。サンプルテキスト。' },
          ],
        },
        {
          id: 'contact_cta',
          type: 'text_image',
          label: 'Contact CTA',
          selector: '.bg-image1',
          heading: { main: 'まずは、お気軽にご相談ください。', sub: 'CONTACT' },
          body: 'ご相談・お見積りは無料です。課題の整理段階でも構いません。\n私たちが、最適な一歩をご一緒します。',
          image: 'images/contact-bg.jpg',
          buttons: [
            { text: 'お問い合わせフォームへ', href: 'contact.html' },
            { text: 'サービス資料のダウンロード', href: '#' },
          ],
        },
        {
          id: 'footer_block',
          type: 'footer_access',
          label: 'Footer',
          ref: 'sharedBlocks.footer',
          selector: 'footer',
        },
      ],
    },
    {
      id: 'contact',
      file: 'contact.html',
      slug: 'contact',
      title: 'Liên hệ',
      titleJa: 'CONTACT',
      isHome: false,
      category: 'main',
      hasHero: false,
      layout: 'single-column',
      description: 'Trang form liên hệ mẫu',
      sections: [
        {
          id: 'contact_form',
          type: 'contact_form',
          label: 'Form liên hệ',
          selector: '.contact-form-block',
          heading: { main: 'お問い合わせフォーム', sub: '' },
          fields: [
            { key: 'name', label: 'お名前', required: true, type: 'text' },
            { key: 'email', label: 'メールアドレス', required: true, type: 'email' },
            { key: 'message', label: 'お問い合わせ内容', required: true, type: 'textarea' },
          ],
          submitText: '内容を確認する',
        },
      ],
    },
    {
      id: '_readme',
      file: '_readme.html',
      slug: '_readme',
      title: 'Readme',
      category: 'system',
      isHome: false,
      hasHero: false,
      hidden: true,
      description: 'Hướng dẫn template',
      sections: [],
    },
  ],
};

export default XANH_DARK_LP_KAISHAINTRO_REGISTRY;
