/**
 * Registry — xanh_LP_business_kaishaintro (tp_biz64)
 * Thư mục: frontend/template/xanh_LP_business_kaishaintro/
 */

export const XANH_LP_BUSINESS_KAISHAINTRO_FOLDER = 'xanh_LP_business_kaishaintro';

export const XANH_LP_BUSINESS_KAISHAINTRO_REGISTRY = {
  templateKey: 'xanh_lp_business_kaishaintro',
  folder: XANH_LP_BUSINESS_KAISHAINTRO_FOLDER,
  renderMode: 'html',
  layout: 'biz64',
  name: 'LP Kaisha Intro — Xanh',
  description: 'Corporate tp_biz64 — hero slide, services, about, workflow, FAQ, news, contact',
  previewColor: '#1962bf',
  assets: {
    css: ['css/style.css'],
    js: ['js/jquery.inview_set.js', 'js/main.js'],
    externalJs: [
      'https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js',
      'https://cdnjs.cloudflare.com/ajax/libs/protonet-jquery.inview/1.1.2/jquery.inview.min.js',
    ],
    externalCss: [
      'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css',
    ],
  },
  sharedBlocks: {
    header: {
      id: 'header',
      type: 'header',
      label: 'Header & Menu',
      logoSelector: 'h1.logo a, .logo a',
      logoType: 'image',
      navSelector: 'header nav > ul',
    },
    footer: {
      id: 'footer',
      type: 'footer',
      label: 'Footer',
      addressSelector: 'footer .address p:not(.logo)',
      menuSelector: 'footer .menu',
      copyrightSelector: 'footer small',
      snsSelector: 'footer .sns1-parts, footer .sns',
    },
    hero: {
      id: 'hero',
      type: 'hero_slide',
      label: 'Hero / Main image',
      selector: '.mainimg',
      defaultSlide: {
        headline: 'ビジネスの未来を、\nともに創る。',
        subheadline: 'シンプルに、わかりやすく、成果に繋げる。',
        body: '私たちは、お客様の課題に寄り添い、最適なソリューションで持続的な成長をサポートします。',
        ctaPrimary: 'サービスを見る',
        ctaSecondary: 'お問い合わせ',
        ctaPrimaryHref: '#link1',
        ctaSecondaryHref: 'contact.html',
        image: 'images/mainimg1.jpg',
        imageMobile: 'images/mainimg1_s.jpg',
        slideClass: 'img1',
      },
    },
  },
  nav: [
    { label: 'サービス', pageId: 'index', anchor: 'link1' },
    { label: '私たちについて', pageId: 'index', anchor: 'link2' },
    { label: 'サービスの流れ', pageId: 'index', anchor: 'link3' },
    { label: 'よく頂く質問', pageId: 'index', anchor: 'link4' },
    { label: 'お問い合わせ', pageId: 'contact', href: 'contact.html' },
  ],
  pages: [
    {
      id: 'index',
      file: 'index.html',
      slug: '',
      title: 'Trang chủ',
      titleJa: 'HOME',
      isHome: true,
      category: 'main',
      hasHero: true,
      bodyClass: 'home',
      layout: 'single-page-scroll',
      description: 'Landing tp_biz64: hero, services, about, workflow, FAQ, contact CTA, news',
      previewImage: '/template/xanh_LP_business_kaishaintro/images/mainimg1.jpg',
      sections: [
        { id: 'hero', type: 'hero_slide', ref: 'sharedBlocks.hero', label: 'Hero / Main image' },
        {
          id: 'services',
          type: 'icon_list',
          label: 'Services (サービスの特徴)',
          selector: '#link1 .list1',
          anchor: 'link1',
          heading: { main: 'サービスの特徴', sub: 'Service' },
          items: [
            { title: 'コンサルティング', body: '課題の整理から戦略立案まで、実行可能な解決策をご提案します。', icon: 'fas fa-chart-column', href: '#', linkText: '詳細を見る' },
            { title: 'システム開発', body: '業務に最適なシステムを設計・開発し、業務効率化を実現します。', icon: 'fas fa-desktop', href: '#', linkText: '詳細を見る' },
            { title: '運用サポート', body: '導入後の運用・改善まで伴走し、安心のサポートを提供します。', icon: 'fas fa-users', href: '#', linkText: '詳細を見る' },
          ],
        },
        {
          id: 'about',
          type: 'text_image',
          label: 'About (私たちについて)',
          selector: '#link2 .flex1',
          anchor: 'link2',
          heading: { main: 'お客様の成長に、確かな価値を。', sub: '私たちについて' },
          body: 'SAMPLE株式会社は、幅広い業界の企業様をご支援してきた実績と専門知識を活かし、ビジネスの成長を支えます。\n信頼されるパートナーとして、誠実に、丁寧に、最適なサービスをご提供します。',
          image: 'images/img1.jpg',
          buttonText: '私たちについて',
          buttonLink: '#',
        },
        {
          id: 'workflow',
          type: 'step_list',
          label: 'Workflow (サービスの流れ)',
          selector: '#link3 .step1',
          anchor: 'link3',
          heading: { main: 'サービスの流れ', sub: '' },
          steps: [
            { step: '01', title: 'ヒアリング', body: 'お客様の課題や要望を丁寧にヒアリングします。', icon: 'fas fa-comments' },
            { step: '02', title: 'ご提案', body: '課題に合わせた最適なプランをご提案します。', icon: 'fas fa-clipboard-list' },
            { step: '03', title: '実行・導入', body: '計画に基づき、開発・導入をスムーズに進めます。', icon: 'fas fa-cog' },
            { step: '04', title: '運用・改善', body: '導入後も継続的にサポートし、効果の最大化を支援します。', icon: 'fas fa-chart-column' },
          ],
        },
        {
          id: 'faq',
          type: 'faq_accordion',
          label: 'FAQ (よく頂く質問)',
          selector: '#link4 dl',
          anchor: 'link4',
          heading: { main: 'よく頂く質問', sub: '' },
          items: [
            { question: 'ここに質問を書きます。クリックで回答が開きます。', answer: 'ここに回答を書きます。サンプルテキスト。ここに回答を書きます。サンプルテキスト。ここに回答を書きます。サンプルテキスト。' },
            { question: 'ここに質問を書きます。クリックで回答が開きます。', answer: 'ここに回答を書きます。サンプルテキスト。ここに回答を書きます。サンプルテキスト。ここに回答を書きます。サンプルテキスト。' },
            { question: 'ここに質問を書きます。クリックで回答が開きます。', answer: 'ここに回答を書きます。サンプルテキスト。ここに回答を書きます。サンプルテキスト。' },
          ],
        },
        {
          id: 'contact_cta',
          type: 'cta_banner',
          label: 'Contact CTA',
          selector: 'section.contact',
          heading: { main: 'まずはお気軽にご相談ください', sub: '' },
          body: '課題の整理からでも構いません。私たちが最適な解決策をご提案します。',
          buttons: [{ text: 'お問い合わせはこちら', href: 'contact.html' }],
        },
        {
          id: 'news',
          type: 'news_list',
          label: 'News (お知らせ)',
          selector: 'dl.news',
          heading: { main: 'お知らせ', sub: '' },
          items: [
            { date: '2026/05/26', body: '開閉メニューでページ内リンク（アンカーリンク）を使った場合に、スマホでメニューが閉じない不具合があったので改善。' },
            { date: '2026/04/06', tag: 'その他', body: 'ビジネス向け 無料ホームページテンプレート tp_biz64 公開。' },
            { date: '2000/00/00', tagClass: 'accent-color', tag: '重要', body: 'サンプルテキスト。サンプルテキスト。サンプルテキスト。' },
          ],
        },
        {
          id: 'footer_block',
          type: 'footer_access',
          label: 'Footer',
          ref: 'sharedBlocks.footer',
          selector: 'footer',
        },
      ],
    },
    {
      id: 'contact',
      file: 'contact.html',
      slug: 'contact',
      title: 'Liên hệ',
      titleJa: 'CONTACT',
      isHome: false,
      category: 'main',
      hasHero: false,
      layout: 'single-column',
      description: 'Trang form liên hệ mẫu',
      sections: [
        {
          id: 'contact_form',
          type: 'contact_form',
          label: 'Form liên hệ',
          selector: '.contact-form-block',
          heading: { main: 'お問い合わせフォーム', sub: '' },
          fields: [
            { key: 'name', label: 'お名前', required: true, type: 'text' },
            { key: 'email', label: 'メールアドレス', required: true, type: 'email' },
            { key: 'message', label: 'お問い合わせ内容', required: true, type: 'textarea' },
          ],
          submitText: 'この内容で送信する',
        },
      ],
    },
    {
      id: '_readme',
      file: '_readme.html',
      slug: '_readme',
      title: 'Readme',
      category: 'system',
      isHome: false,
      hasHero: false,
      hidden: true,
      description: 'Hướng dẫn template',
      sections: [],
    },
  ],
};

export default XANH_LP_BUSINESS_KAISHAINTRO_REGISTRY;
