/** Marketing copy aligned with JobShare_Login_V1 / Candidate_Login_V2 templates. */

export const COLLABORATOR_LOGIN_COPY = {
  vi: {
    back: 'Quay lại trang chủ',
    kicker: 'WORKSTATION JOBSHARE',
    title: 'Đăng nhập CTV',
    email: 'Email',
    password: 'Mật khẩu',
    login: 'Đăng nhập',
    loggingIn: 'Đang đăng nhập...',
    forgot: 'Quên mật khẩu? Nhấn vào đây',
    register: 'Đăng ký mới? Nhấn vào đây',
    failed: 'Đăng nhập thất bại. Vui lòng thử lại.',
    failedCheck: 'Đăng nhập thất bại. Vui lòng kiểm tra lại thông tin.',
    required: 'Vui lòng nhập đầy đủ email và mật khẩu',
    forgotTitle: 'Quên mật khẩu',
    forgotDesc: 'Nhập email đã đăng ký để nhận liên kết đặt lại mật khẩu.',
    sendReset: 'Gửi liên kết đặt lại',
    sending: 'Đang gửi...',
    backLogin: 'Quay lại đăng nhập',
    showPassword: 'Hiển thị mật khẩu',
    hidePassword: 'Ẩn mật khẩu',
  },
  en: {
    back: 'Back to home',
    kicker: 'WORKSTATION JOBSHARE',
    title: 'Agent Login',
    email: 'Email',
    password: 'Password',
    login: 'Login',
    loggingIn: 'Logging in...',
    forgot: 'Forgot password? Click here',
    register: 'New registration? Click here',
    failed: 'Login failed. Please try again.',
    failedCheck: 'Login failed. Please check your information.',
    required: 'Please enter email and password',
    forgotTitle: 'Forgot Password',
    forgotDesc: 'Enter your registered email to receive a password reset link.',
    sendReset: 'Send Reset Link',
    sending: 'Sending...',
    backLogin: 'Back to Login',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
  },
  ja: {
    back: 'ホームに戻る',
    kicker: 'WORKSTATION JOBSHARE',
    title: 'エージェントログイン',
    email: 'Email',
    password: 'パスワード',
    login: 'ログイン',
    loggingIn: 'ログイン中...',
    forgot: 'パスワードをお忘れですか？ここをクリック',
    register: '新規登録？ここをクリック',
    failed: 'ログインに失敗しました。もう一度お試しください。',
    failedCheck: 'ログインに失敗しました。情報を確認してください。',
    required: 'メールアドレスとパスワードを入力してください',
    forgotTitle: 'パスワードをお忘れの場合',
    forgotDesc: '登録したメールアドレスを入力して、パスワードリセットリンクを受け取ってください。',
    sendReset: 'リセットリンクを送信',
    sending: '送信中...',
    backLogin: 'ログインに戻る',
    showPassword: 'パスワードを表示',
    hidePassword: 'パスワードを非表示',
  },
};

export const CANDIDATE_LOGIN_COPY = {
  vi: {
    back: 'Quay lại trang chủ',
    kicker: 'WORKSTATION JOBSHARE',
    title: 'Đăng nhập ứng viên',
    pageTitle: 'Đăng nhập ứng viên | Workstation JobShare',
    email: 'Email',
    password: 'Mật khẩu',
    login: 'Đăng nhập',
    loggingIn: 'Đang đăng nhập...',
    forgot: 'Quên mật khẩu? Nhấn vào đây',
    register: 'Đăng ký mới? Nhấn vào đây',
    failed: 'Đăng nhập thất bại. Vui lòng thử lại.',
    failedCheck: 'Đăng nhập thất bại. Vui lòng kiểm tra lại thông tin.',
    required: 'Vui lòng nhập đầy đủ email và mật khẩu',
    forgotTitle: 'Quên mật khẩu',
    forgotDesc: 'Nhập email đã đăng ký để nhận liên kết đặt lại mật khẩu.',
    sendReset: 'Gửi liên kết đặt lại',
    sending: 'Đang gửi...',
    backLogin: 'Quay lại đăng nhập',
    showPassword: 'Hiển thị mật khẩu',
    hidePassword: 'Ẩn mật khẩu',
  },
  en: {
    back: 'Back to home',
    kicker: 'WORKSTATION JOBSHARE',
    title: 'Candidate Sign In',
    pageTitle: 'Candidate Sign In | Workstation JobShare',
    email: 'Email',
    password: 'Password',
    login: 'Login',
    loggingIn: 'Logging in...',
    forgot: 'Forgot password? Click here',
    register: 'New registration? Click here',
    failed: 'Login failed. Please try again.',
    failedCheck: 'Login failed. Please check your information.',
    required: 'Please enter email and password',
    forgotTitle: 'Forgot Password',
    forgotDesc: 'Enter your registered email to receive a password reset link.',
    sendReset: 'Send Reset Link',
    sending: 'Sending...',
    backLogin: 'Back to Login',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
  },
  ja: {
    back: 'ホームに戻る',
    kicker: 'WORKSTATION JOBSHARE',
    title: '応募者ログイン',
    pageTitle: '応募者ログイン | Workstation JobShare',
    email: 'Email',
    password: 'パスワード',
    login: 'ログイン',
    loggingIn: 'ログイン中...',
    forgot: 'パスワードをお忘れですか？ここをクリック',
    register: '新規登録？ここをクリック',
    failed: 'ログインに失敗しました。もう一度お試しください。',
    failedCheck: 'ログインに失敗しました。情報を確認してください。',
    required: 'メールアドレスとパスワードを入力してください',
    forgotTitle: 'パスワードをお忘れの場合',
    forgotDesc: '登録したメールアドレスを入力して、パスワードリセットリンクを受け取ってください。',
    sendReset: 'リセットリンクを送信',
    sending: '送信中...',
    backLogin: 'ログインに戻る',
    showPassword: 'パスワードを表示',
    hidePassword: 'パスワードを非表示',
  },
};

export const LOGIN_TEMPLATE_ASSETS = {
  collaborator: {
    publicBase: '/landing/login-collaborator-v1',
    brandImage: 'login-collaborator.webp',
    shellLabel: 'JobShare login',
  },
  candidate: {
    publicBase: '/landing/login-candidate-v2',
    brandImage: 'login-candidate.webp',
    shellLabel: 'JobShare Candidate login',
  },
};
