"""Source-authoritative rendering. Marketing content lives only in source-content.json."""
from pathlib import Path
from html import escape
import json,re
from PIL import Image
ROOT=Path(__file__).resolve().parent
SOURCE=json.loads((ROOT/'source-content.json').read_text())
UI=json.loads((ROOT/'ui-content.json').read_text())
SUPPORT=json.loads((ROOT/'support-content.json').read_text())
POLICY=json.loads((ROOT/'policy-content.json').read_text())
NEWS=json.loads((ROOT/'news.json').read_text())
ICONS=json.loads((ROOT/'icons.json').read_text())
PARTNERS=['Link Trust','Koyo Engineering','EXEO Engineering West Japan','TechnoPro Construction','Nuvoton','TechnoPro Design','TechnoPro IT','ACA Next','GMO-Z.com Trust Company','Rakus','BREXA Technology','B-Next Technologies','Staff Service Engineering','Quest Global','Persol Excel HR Partners','Meitec Fielders','Unlock Design','VMO Japan']
REG='https://ws-jobshare.com/register'
def e(s):return escape(str(s),quote=True)
def icon(n):return '<svg aria-hidden="true" viewBox="0 0 24 24">'+ICONS[n]+'</svg>'
def img(src,alt,lazy=True):
 with Image.open(ROOT/src) as im:w,h=im.size
 return f'<img src="{src}" alt="{e(alt)}" width="{w}" height="{h}" {"loading=lazy" if lazy else "fetchpriority=high"} decoding="async">'
def heading(s):return str(s).rstrip().rstrip('.。')
def numbered(n):return f'<span class="section-number" aria-hidden="true">{n:02d}</span>'
for lang,t in SOURCE.items():
 u=UI[lang];chat=SUPPORT[lang];base='https://ws-jobshare.com/'+lang;local='index.html' if lang=='vi' else 'index-'+lang+'.html'
 def S(key,tag='p',cls='',head=False):return f'<{tag} class="{cls}" data-source="{key}">{e(heading(t[key]) if head else t[key])}</{tag}>'
 def H(keys,cls=''):
  return f'<h2 class="{cls}">'+''.join(f'<span class="semantic-line" data-source="{k}">{e(heading(t[k]))}</span>' for k in keys)+'</h2>'
 def A(key,url,primary=True):return f'<a class="btn {"btn-primary" if primary else "btn-quiet"}" data-source="{key}" href="{e(url)}">{e(t[key])}</a>'
 def B(key,action):return f'<button class="btn btn-quiet" type="button" data-source="{key}" data-action="{action}">{e(t[key])}</button>'
 roles=''.join(f'<a class="role" href="{url}" {"aria-current=page" if i==0 else ""}>{icon(["people","user","brief"][i])}<span><strong>{e(u["roles"][i])}</strong><small>{e(u["roleSub"][i])}</small></span></a>' for i,url in enumerate([local,base+'/candidate','https://ws-jobshare.com/business']))
 langs=''.join(f'<a href="{"index.html" if l=="vi" else "index-"+l+".html"}" lang="{l}" hreflang="{l}" {"aria-current=page" if l==lang else ""}>{l.upper()}</a>' for l in ['vi','en','ja'])
 nav=''.join(f'<a href="{url}">{e(u[k])}</a>' for k,url in [('navHome','#top'),('navJobs',base+'/jobs'),('navAbout',base+'/about-us'),('navFaq','#faq'),('navBlog','#news')])+f'<a class="nav-login" href="https://ws-jobshare.com/login">{e(u["login"])}</a>'
 community=''.join(f'<article class="community-card" data-reveal style="--delay:{(i-1)*65}ms"><div class="card-top"><span class="card-number">0{i}</span>{icon(ic)}</div>{S("aboutCard"+str(i)+"Title","h3",head=True)}{S("aboutCard"+str(i)+"Desc")}</article>' for i,ic in enumerate(['search','progress','ai'],1))
 why=''.join(f'<article class="why-card" data-reveal><div class="card-top"><span class="card-number">0{i}</span>{icon(ic)}</div>{S("whyCard"+str(i)+"Title","h3",head=True)}{S("whyCard"+str(i)+"Desc")}</article>' for i,ic in zip(range(2,5),['user','people','brief']))
 steps=''.join(f'<article class="flow-step" data-reveal style="--delay:{(i-1)*80}ms"><div class="step-top"><span class="step-no">0{i}</span>{icon(ic)}</div>{S("guideStep"+str(i)+"Title","h3",head=True)}{S("guideStep"+str(i)+"Desc")}</article>' for i,ic in enumerate(['user','search','progress'],1))
 features=''.join(f'<article class="feature" data-reveal><div class="feature-heading"><span class="card-number">0{i}</span>{S("feature"+str(i)+"Title","h3",head=True)}</div>{S("feature"+str(i)+"Desc")}<ul class="check-list">'+''.join(f'<li data-source="feature{i}Points.{j}">{e(x)}</li>' for j,x in enumerate(t['feature'+str(i)+'Points']))+'</ul></article>' for i in range(1,5))
 logos=''.join(f'<div class="partner" title="{e(name)}">{img("assets/partner-"+str(i+1)+".png",name)}</div>' for i,name in enumerate(PARTNERS))
 news=''.join(f'<a class="news-card" href="{e(n["urls"][lang])}" data-news-id="{n["id"]}" data-reveal><div class="news-image">{img(n["image"],n["title"][lang])}</div><div class="news-body"><div class="news-meta"><time datetime="{n["date"]}">{n["date"].replace("-",".")}</time><span>· {e(t["hotNewsTagFallback"])}</span></div><h3>{e(n["title"][lang])}</h3></div></a>' for n in NEWS)
 faqs=''.join(f'<details><summary><span class="q" aria-hidden="true">Q</span><span data-source="faqItems.{i}.q">{e(f["q"])}</span></summary><div class="faq-answer">'+''.join(f'<p data-source="faqItems.{i}.paragraphs.{j}">{e(p)}</p>' for j,p in enumerate(f['paragraphs']))+'</div></details>' for i,f in enumerate(t['faqItems']))
 footerlinks=''.join(f'<li><a data-source="footerExploreLinks.{i}" href="{url}">{e(label)}</a></li>' for i,(url,label) in enumerate(zip([base+'/jobs',base+'/about-us','#partners',base+'/blog'],t['footerExploreLinks'])))
 # Keep exact source words; whitespace only differs by language composition.
 sep='' if lang=='ja' else ' '
 hero1=sep.join([t['heroTitleRed1'],t['heroTitleWhite1']]);hero2=sep.join([t['heroTitleWhite2'],t['heroTitleRed2']])
 final1=t['footerCtaTitleWhite'];final2=t['footerCtaTitleRed'];finalend=t['footerCtaTitleWhiteEnd']
 messenger='<svg aria-hidden="true" viewBox="0 0 24 24" class="messenger-icon"><path d="M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719"/></svg>'
 greeting=chat['greeting'].replace('${n}',chat['guest'])
 support_options=''.join(f'<details class="support-question"><summary>{e(chat["opt"+str(i)])}</summary><div>'+(
 e(chat['opt1ReplyLead'])+f'<button type="button" class="text-link" data-action="policy">{e(chat["linkPolicy"])}</button>'+e(chat['opt1ReplyTail']) if i==1 else e(chat['opt2Reply']) if i==2 else e(chat['opt3ReplyLead'])+f'<a href="{base}/blog">{e(chat["opt3LinkNews"])}</a>'+e(chat['opt3ReplyTail']) if i==3 else e(chat['opt4ContactIntro'])+f'<p><a href="tel:+84972899728">{e(chat["opt4HotlineVn"])}</a></p><p><a href="tel:+819094411975">{e(chat["opt4HotlineJp"])}</a></p><p><a href="https://www.facebook.com/" target="_blank" rel="noopener noreferrer">{e(chat["opt4Facebook"])}</a></p>'
 )+'</div></details>' for i in range(1,5))
 html=f'''<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(t['heroBadge'])} | JobShare</title><meta name="description" content="{e(t['heroDesc'])}"><meta name="theme-color" content="#ed212f"><link rel="icon" href="assets/jobshare-logo.png"><link rel="stylesheet" href="fonts.css"><link rel="stylesheet" href="styles.css"><script src="app.js" defer></script></head>
<body lang="{lang}" id="top"><a class="skip" href="#main">{e(u['skip'])}</a>
<div class="role-bar"><div class="wrap role-intro">{e(u['roleIntro'])}</div><nav class="wrap roles" aria-label="{e('/'.join(u['roles']))}">{roles}</nav></div>
<header class="site-header"><div class="wrap header-inner"><a class="brand" href="{local}" aria-label="JobShare">{img('assets/jobshare-logo.png','JobShare',False)}</a><nav class="nav" id="main-nav" aria-label="{e(u['openMenu'])}">{nav}</nav><div class="header-tools"><div class="languages" aria-label="Language">{langs}</div><a class="login" href="https://ws-jobshare.com/login">{e(u['login'])}</a><a class="header-register" href="{REG}">{e(u['register'])}</a><button class="menu-btn" aria-label="{e(u['openMenu'])}" aria-controls="main-nav" aria-expanded="false">{icon('menu')}</button></div></div></header>
<main id="main">
<section class="hero" id="hero"><div class="wrap hero-grid"><div class="hero-copy">{S('heroBadge','p','kicker')}<h1><span class="hero-line">{e(hero1)}</span><span class="hero-line">{e(hero2)}</span></h1>{S('heroDesc','p','hero-lead')}<div class="actions">{A('heroBtnPrimary',REG)}{A('heroBtnSecondary','#guide',False)}</div></div><figure class="hero-media">{img('assets/hero.webp',u['heroAlt'],False)}</figure></div></section>
<section class="section community" id="community"><div class="wrap"><div class="source-section-head" data-reveal>{numbered(1)}{H(['aboutTitleLine1','aboutTitleLine2'])}</div><div class="community-grid">{community}</div></div></section>
<section class="section why-section" id="why"><div class="wrap"><div class="section-head" data-reveal><div>{numbered(2)}{S('whyTitle','h2',head=True)}</div>{S('whyDesc')}</div><div class="why-grid"><article class="why-card commission-card" data-reveal><div class="commission-copy"><div class="card-top"><span class="card-number">01</span>{icon('progress')}</div>{S('whyCard1Title','h3',head=True)}{S('whyCard1Desc')}</div><div class="commission-board"><div class="commission-value"><strong>25<span>%</span></strong><p>{e(u['starting'])}</p></div><span class="commission-dash" aria-hidden="true"></span><div class="commission-value"><strong>50<span>%</span></strong><p>{e(u['maximum'])}</p></div></div></article>{why}</div></div></section>
<section class="section ai-section" id="ai-cv"><div class="wrap split"><figure class="media-frame" data-reveal>{img('assets/ai-cv.webp',u['aiAlt'])}</figure><div class="split-copy" data-reveal>{numbered(3)}{S('aiCvPromoTitle','h2',head=True)}<div class="actions">{A('aiCvPromoCta',REG)}</div></div></div></section>
<section class="section flow" id="guide"><div class="wrap"><div class="source-section-head" data-reveal>{numbered(4)}{H(['guideTitleLine1','guideTitleLine2'])}</div><div class="flow-board">{steps}</div></div></section>
<section class="section platform" id="features"><div class="wrap"><div class="platform-intro"><div data-reveal>{numbered(5)}{S('featureTitle','h2',head=True)}<div class="actions">{A('featureCta',REG)}</div></div><figure class="media-frame" data-reveal>{img('assets/network.webp',u['platformAlt'])}</figure></div><div class="features">{features}</div></div></section>
<section class="section partners" id="partners"><div class="wrap"><div class="source-section-head" data-reveal>{numbered(6)}{H(['partnerTitleLine1','partnerTitleLine2'])}</div><div class="partner-grid">{logos}</div></div></section>
<section class="section news" id="news"><div class="wrap"><div class="section-head" data-reveal><div>{numbered(7)}{S('hotNewsTitle','h2',head=True)}</div><div>{S('hotNewsDesc')}<a class="text-link" data-source="hotNewsViewAll" href="{base}/blog">{e(t['hotNewsViewAll'])}</a></div></div><div class="news-grid">{news}</div></div></section>
<section class="section faq-section" id="faq"><div class="wrap faq-grid"><div class="faq-title" data-reveal>{numbered(8)}{S('faqTitle','h2',head=True)}</div><div class="faq-list" data-reveal>{faqs}</div></div></section>
<section class="final" id="final"><div class="wrap"><div class="final-box" data-reveal><figure class="final-media">{img('assets/support.webp',u['finalAlt'])}</figure><div class="final-copy"><h2>{e(final1)}{sep}<span>{e(final2)}</span>{sep if lang!='ja' and finalend!='?' else ''}{e(finalend)}</h2>{S('footerCtaDesc')}<div class="actions">{A('footerBtnPrimary',REG)}{B('footerBtnSecondary','contact')}</div></div></div></div></section>
</main><footer class="site-footer"><div class="wrap"><div class="footer-grid"><div class="footer-brand">{img('assets/jobshare-white.png','JobShare')}{S('footerDesc')}</div><div>{S('footerExploreTitle','h3',head=True)}<ul>{footerlinks}</ul></div><div>{S('footerSupportTitle','h3',head=True)}<ul><li><a href="#guide" data-source="footerSupportLinks.0">{e(t['footerSupportLinks'][0])}</a></li><li><a href="#faq" data-source="footerSupportLinks.1">{e(t['footerSupportLinks'][1])}</a></li><li><a href="#" data-source="footerSupportLinks.2">{e(t['footerSupportLinks'][2])}</a></li><li><button class="footer-contact" data-action="contact" data-source="footerSupportLinks.3">{e(t['footerSupportLinks'][3])}</button></li></ul></div><div>{S('footerContactTitle','h3',head=True)}{S('footerContactLocation','address')}{S('footerContactInfoTitle','p','footer-subtitle')}<a class="footer-phone" href="tel:+84972899728" data-source="footerContactPhone">{e(t['footerContactPhone'])}</a></div></div><div class="footer-bottom"><span>© 2026 Workstation JobShare</span><a href="https://ws-jobshare.com/" data-source="footerLinkUrl">{e(t['footerLinkUrl'])}</a></div></div></footer>
<div class="floating-controls"><a class="back-top" href="#top" aria-label="{e(u['top'])}">{icon('up')}</a><button class="support-launcher" type="button" aria-controls="support-panel" aria-expanded="false" aria-label="{e(chat['openAria'])}">{messenger}<span>{e(chat['title'])}</span></button></div>
<section class="support-panel" id="support-panel" role="dialog" aria-label="{e(chat['title'])}" hidden><header><div><strong>{e(chat['title'])}</strong><p>{e(chat['subtitle'])}</p></div><button class="support-close" aria-label="{e(chat['close'])}">×</button></header><div class="support-tabs" role="tablist"><button role="tab" id="tab-home" aria-selected="true" aria-controls="support-home">{e(chat['tabHome'])}</button><button role="tab" id="tab-messages" aria-selected="false" aria-controls="support-messages">{e(chat['tabMessages'])}</button></div><div id="support-home" role="tabpanel" aria-labelledby="tab-home"><p>{e(greeting)}</p>{support_options}</div><div id="support-messages" role="tabpanel" aria-labelledby="tab-messages" hidden><p class="chat-hint">{e(chat['chatWithAdminHint'])}</p><label class="name-label">{e(chat['yourName'])}<input id="visitor-name" maxlength="100" autocomplete="name"></label><div class="chat-history" role="log" aria-live="polite"></div><form id="support-form"><label class="sr-only" for="chat-body">{e(chat['chatPlaceholder'])}</label><textarea id="chat-body" maxlength="4000" rows="3" placeholder="{e(chat['placeholderFirst'])}" required></textarea><button class="btn btn-primary" type="submit">{e(chat['startChat'])}</button></form><p class="chat-error" role="status" hidden>{e(u['chatError'])}</p><div class="chat-phones"><a href="tel:+84972899728">{e(chat['opt4HotlineVn'])}</a><a href="tel:+819094411975">{e(chat['opt4HotlineJp'])}</a></div></div></section>
<dialog class="contact-dialog"><div class="contact-dialog-inner"><h2>{e(t['footerContactTitle'])}</h2><address>{e(t['footerContactLocation'])}</address><a href="https://ws-jobshare.com/">{e(t['footerLinkUrl'])}</a><a class="footer-phone" href="tel:+84972899728">{e(t['footerContactPhone'])}</a><form method="dialog"><button class="btn btn-primary">OK</button></form></div></dialog>
<script type="application/json" id="chat-config">{json.dumps({'api':'https://ws-jobshare.com/api_jobshare/api','send':chat['send'],'connecting':chat['connecting'],'start':chat['startChat']},ensure_ascii=False)}</script>
</body></html>'''
 policybody=''.join('<section><h3>'+e(row['heading'])+'</h3>'+''.join('<p>'+e(p)+'</p>' for p in row['paragraphs'])+'</section>' for row in POLICY['fhe'][lang])
 policytitle=POLICY['hv']['commission'][{'vi':'titleVi','en':'titleEn','ja':'titleJa'}[lang]]
 html=html.replace('</body>', '<dialog class="policy-dialog"><div class="policy-head"><h2>'+e(policytitle)+'</h2><form method="dialog"><button aria-label="'+e(chat['close'])+'">×</button></form></div><div class="policy-body">'+policybody+'</div></dialog></body>')
 if lang=='ja':
  from ja_typography import apply
  html=apply(html)
 (ROOT/local).write_text(html)
print('Built 3 locales from source-content.json')
